version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: WST_ITPL_client
    ports: 
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  web:
    build: .
    volumes:
      - .:/my_app_dir
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001" #./start.sh
    ports:
      - "8001:8001"
    depends_on:
      - db